#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

$(call inherit-product, $(SRC_TARGET_DIR)/product/core_64_bit.mk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base_telephony.mk)
$(call inherit-product, device/doogee/s88pro/device.mk)
$(call inherit-product, vendor/lineage/config/common_full_phone.mk)

PRODUCT_DEVICE := s88pro
PRODUCT_NAME := lineage_s88pro
PRODUCT_BRAND := DOOGEE
PRODUCT_MODEL := S88Pro
PRODUCT_MANUFACTURER := doogee

PRODUCT_GMS_CLIENTID_BASE := android-doogee

# Stock fingerprint, verified in Phase 1. Some apps and the RIL read it.
#
# The key is BuildDesc, not the PRIVATE_BUILD_DESC of LineageOS 21. build.prop
# is generated by soong now, and build/soong/scripts/gen_build_prop.py accepts
# an override only for a key it already holds, or it stops the build:
#
#   Key "PRIVATE_BUILD_DESC" isn't a valid prop override
#
# BuildDesc is the one it computes for ro.build.description, and override_config()
# runs after it is computed, so overriding it takes.
PRODUCT_BUILD_PROP_OVERRIDES += \
    BuildDesc="S88Pro_EEA-user 10 QP1A.190711.020 1592876742 release-keys"

BUILD_FINGERPRINT := DOOGEE/S88Pro_EEA/S88Pro:10/QP1A.190711.020/1592876742:user/release-keys
