#!/usr/bin/env bash
#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#
# Generates the vendor/doogee/s88pro makefiles from proprietary-files.txt.
#
# THE DESTINATION COMES FROM THE PATH. This script used to send everything to
# $(TARGET_COPY_OUT_SYSTEM), because the list held only the MediaTek framework
# .jars. Now that the 1622 files of the vendor partition are there too, the
# prefix decides where a file goes: "vendor/..." to TARGET_COPY_OUT_VENDOR,
# "system/..." to TARGET_COPY_OUT_SYSTEM, and so on. Getting it wrong raises
# no error: the files land in the wrong partition and the phone does not boot,
# which is worse.
#
# WHY .so FILES NOW GO THROUGH PRODUCT_COPY_FILES TOO. Every library used to
# become a BUILD_PREBUILT module, because the build rejects ELF files in
# PRODUCT_COPY_FILES with
#   FAILED: ...check-non-elf-file-timestamps.../lib64/libXXX.so.timestamp
# With 947 libraries that route does not scale: 586 have a unique basename, the
# other 361 collide (the same library in lib and lib64, or in hw/ and at the
# root), and two modules with the same LOCAL_MODULE override each other.
# AOSP has a switch for exactly this -- BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES,
# in build/make/core/board_config.mk -- and it is enabled in BoardConfig.
#
# Only APKs stay modules, since PRODUCT_COPY_FILES rejects them regardless:
#   error: Prebuilt apk found in PRODUCT_COPY_FILES: ... use BUILD_PREBUILT instead!
#
# Symlinks cannot be expressed in a file list: they are at the bottom of this
# script, written by hand, and become a module that creates them after
# installation.
set -euo pipefail

DEVICE=s88pro
VENDOR=doogee
HERE="$(cd "$(dirname "$0")" && pwd)"
LIST="$HERE/proprietary-files.txt"
OUT="$HERE/../../../vendor/$VENDOR/$DEVICE"

mkdir -p "$OUT"

# Looks for a DESTINATION path in the list. grep -x cannot be used: a line may
# be "system/lib64/x.so" or "product/lib64/x.so:system/lib64/x.so", and the
# second form would never match.
listed() {                       # $1 = destination path
	awk -v p="$1" '
		/^[[:space:]]*(#|$)/ { next }
		{ sub(/^-/, ""); if (index($0, ":")) sub(/^[^:]*:/, "");
		  if ($0 == p) { found = 1; exit } }
		END { exit !found }' "$LIST"
}

# The destination partition, derived from the path prefix.
destination() {                 # $1 = path as it appears in the list
	case "$1" in
		vendor/*)  echo "\$(TARGET_COPY_OUT_VENDOR)/${1#vendor/}" ;;
		system/*)  echo "\$(TARGET_COPY_OUT_SYSTEM)/${1#system/}" ;;
		product/*) echo "\$(TARGET_COPY_OUT_PRODUCT)/${1#product/}" ;;
		odm/*)     echo "\$(TARGET_COPY_OUT_ODM)/${1#odm/}" ;;
		*)         echo "\$(TARGET_COPY_OUT_SYSTEM)/$1" ;;
	esac
}

# --- Android.mk: the APKs and the symlinks ---
{
	cat << 'HEADER'
# Generated by device/doogee/s88pro/setup-makefiles.sh — do not edit by hand.

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),s88pro)

HEADER

	while read -r line; do
		case "$line" in ''|'#'*) continue ;; esac
		f="${line#-}"
		case "$f" in *:*) f="${f#*:}" ;; esac
		case "$f" in
			system/*.so)
				# Libraries that end up in system stay modules: other modules depend
				# on them by name, and with a plain copy the build stops with
				#   TARGET module FMRadio requires non-existent TARGET module: libfmjni:64
				# There are eight; the vendor's 947 go through PRODUCT_COPY_FILES.
				name="$(basename "$f" .so)"
				case "$f" in *lib64*) bits=64 ;; *) bits=32 ;; esac
				other="$(echo "$f" | sed 's#/lib64/#/lib/#')"
				if [ "$bits" = "32" ] && listed "$(echo "$f" | sed 's#/lib/#/lib64/#')"; then
					continue
				fi
				if [ "$bits" = "64" ] && listed "$other"; then
					cat << MODULE
include \$(CLEAR_VARS)
LOCAL_MODULE := $name
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES_64 := proprietary/$f
LOCAL_SRC_FILES_32 := proprietary/$other
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB := both
LOCAL_MODULE_TAGS := optional
LOCAL_STRIP_MODULE := false
LOCAL_CHECK_ELF_FILES := false
include \$(BUILD_PREBUILT)

MODULE
					continue
				fi
				cat << MODULE
include \$(CLEAR_VARS)
LOCAL_MODULE := $name
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := proprietary/$f
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MULTILIB := $bits
LOCAL_MODULE_TAGS := optional
LOCAL_STRIP_MODULE := false
LOCAL_CHECK_ELF_FILES := false
include \$(BUILD_PREBUILT)

MODULE
				;;
			*.apk)
				name="$(basename "$f" .apk)"
				proprietary=""
				case "$f" in vendor/*) proprietary="LOCAL_PROPRIETARY_MODULE := true" ;; esac
				# Privileged or not is decided by the path: priv-app or app. With
				# LOCAL_PRIVILEGED_MODULE the apk ends up in priv-app regardless, and
				# SensorHub -- which in stock lives in vendor/app -- vanished from there
				# without an error.
				privileged=""
				case "$f" in */priv-app/*) privileged="LOCAL_PRIVILEGED_MODULE := true" ;; esac
				# RRO overlays must not be signed with the platform key nor made
				# privileged: they are resources, not applications.
				case "$f" in
					*overlay*)
						cat << MODULE
include \$(CLEAR_VARS)
LOCAL_MODULE := $name
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := proprietary/$f
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_TAGS := optional
LOCAL_DEX_PREOPT := false
$proprietary
LOCAL_MODULE_PATH := \$(TARGET_OUT_VENDOR)/overlay
include \$(BUILD_PREBUILT)

MODULE
						;;
					*)
						cat << MODULE
include \$(CLEAR_VARS)
LOCAL_MODULE := $name
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := proprietary/$f
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := .apk
LOCAL_CERTIFICATE := PRESIGNED
$privileged
LOCAL_MODULE_TAGS := optional
LOCAL_DEX_PREOPT := false
$proprietary
include \$(BUILD_PREBUILT)

MODULE
						;;
				esac
				;;
		esac
	done < "$LIST"

	# The blobs that must beat the AOSP module of the same name. The list is
	# in vendor-override-files.txt, which also explains why.
	if [ -f "$HERE/vendor-override-files.txt" ]; then
		while read -r line; do
			case "$line" in ''|'#'*) continue ;; esac
			f="$line"
			name="$(basename "$f")"
			case "$f" in
				*/bin/*)
					modclass="EXECUTABLES"; dest="\$(TARGET_OUT_VENDOR)/bin/hw"; stem="$name" ;;
				*/lib64/hw/*)
					# The same library exists in lib and lib64: a single module, with
					# MULTILIB both. Two modules with the same LOCAL_MODULE give
					#   error: MODULE.TARGET.SHARED_LIBRARIES.x already defined
					modclass="SHARED_LIBRARIES"; dest=""; stem="$name"
					other32="$(echo "$f" | sed 's#/lib64/#/lib/#')" ;;
				*/lib/hw/*)
					# the 32-bit variant is already covered by the 64-bit one
					continue ;;
				*) continue ;;
			esac
			overridden="${name%.so}"
			if [ "$modclass" = "SHARED_LIBRARIES" ]; then
				sources="LOCAL_SRC_FILES_64 := proprietary/$f
LOCAL_SRC_FILES_32 := proprietary/$other32
LOCAL_MULTILIB := both
LOCAL_MODULE_RELATIVE_PATH := hw"
				modpath=""
			else
				sources="LOCAL_SRC_FILES := proprietary/$f"
				modpath="LOCAL_MODULE_PATH := $dest"
			fi
			# The module has a different name -- otherwise it collides with the one it
			# means to replace -- and LOCAL_MODULE_STEM restores the real file name.
			cat << MODULE
include \$(CLEAR_VARS)
LOCAL_MODULE := s88pro_$overridden
LOCAL_MODULE_STEM := $stem
LOCAL_MODULE_OWNER := $VENDOR
$sources
LOCAL_MODULE_CLASS := $modclass
$modpath
LOCAL_OVERRIDES_MODULES := $overridden
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true
LOCAL_STRIP_MODULE := false
LOCAL_CHECK_ELF_FILES := false
include \$(BUILD_PREBUILT)

MODULE
		done < "$HERE/vendor-override-files.txt"
	fi

	# The stock vendor's symlinks. A file list cannot express them, and copying
	# their content twice would waste space: vulkan points at libGLES_mali.so,
	# which on its own is over twenty megabytes.
	cat << 'LINKS'
# The stock vendor's symlinks.
#
# A file list cannot express them, and copying the content twice would be a
# waste: vulkan points at libGLES_mali.so, which on its own is over twenty
# megabytes. BUILD_PHONY_PACKAGE cannot be used either: with
# LOCAL_PROPRIETARY_MODULE it stops with
#   error: unhandled install path "TARGET_OUT_VENDOR_FAKE"
# because a phony package has nowhere to install itself. That leaves plain
# rules, which is how the other device trees do it anyway.

S88PRO_SYMLINKS :=

define s88pro-symlink
S88PRO_SYMLINKS += $(2)
$(2):
	@mkdir -p $$(dir $$@)
	$$(hide) ln -sf $(1) $$@
endef

$(eval $(call s88pro-symlink,libSoftGatekeeper.so,$(TARGET_OUT_VENDOR)/lib/hw/gatekeeper.default.so))
$(eval $(call s88pro-symlink,libSoftGatekeeper.so,$(TARGET_OUT_VENDOR)/lib64/hw/gatekeeper.default.so))
$(eval $(call s88pro-symlink,gatekeeper.trustkernel.so,$(TARGET_OUT_VENDOR)/lib/hw/gatekeeper.mt6771.so))
$(eval $(call s88pro-symlink,gatekeeper.trustkernel.so,$(TARGET_OUT_VENDOR)/lib64/hw/gatekeeper.mt6771.so))
$(eval $(call s88pro-symlink,gatekeeper.trustkernel.so,$(TARGET_OUT_VENDOR)/lib/hw/gatekeeper.e977_dg_m13_71_q0.so))
$(eval $(call s88pro-symlink,gatekeeper.trustkernel.so,$(TARGET_OUT_VENDOR)/lib64/hw/gatekeeper.e977_dg_m13_71_q0.so))
$(eval $(call s88pro-symlink,kmsetkey.trustkernel.so,$(TARGET_OUT_VENDOR)/lib/hw/kmsetkey.mt6771.so))
$(eval $(call s88pro-symlink,kmsetkey.trustkernel.so,$(TARGET_OUT_VENDOR)/lib64/hw/kmsetkey.mt6771.so))
$(eval $(call s88pro-symlink,/vendor/lib/egl/libGLES_mali.so,$(TARGET_OUT_VENDOR)/lib/hw/vulkan.mt6771.so))
$(eval $(call s88pro-symlink,/vendor/lib64/egl/libGLES_mali.so,$(TARGET_OUT_VENDOR)/lib64/hw/vulkan.mt6771.so))
$(eval $(call s88pro-symlink,/vendor/lib64/libem_sensor_jni.so,$(TARGET_OUT_VENDOR)/app/SensorHub/lib/arm64/libem_sensor_jni.so))
# Note: /vendor/bin/bc exists in stock too, as a symlink to toybox_vendor, but
# it must not be recreated here -- AOSP already makes it, and redefining it gives
#   error: overriding commands for target .../vendor/bin/bc

ALL_DEFAULT_INSTALLED_MODULES += $(S88PRO_SYMLINKS)

endif
LINKS
} > "$OUT/Android.mk"

# --- s88pro-vendor.mk: the copy of everything else ---
{
	cat << 'HEADER'
# Generated by device/doogee/s88pro/setup-makefiles.sh — do not edit by hand.
#
# The stock blobs: the MediaTek framework .jars that go into system, and the
# 1622 files of the vendor partition -- HALs, libraries, firmware,
# configuration and the vendor SELinux policy, without which its services stay silent.

PRODUCT_COPY_FILES += \
HEADER

	while read -r line; do
		case "$line" in ''|'#'*) continue ;; esac
		f="${line#-}"
		case "$f" in *:*) f="${f#*:}" ;; esac
		case "$f" in
			# VINTF files are not copied, the build rejects them:
			#   error: VINTF metadata found in PRODUCT_COPY_FILES: ...
			#   use DEVICE_MANIFEST_FILE / ODM_MANIFEST_FILES / vintf_fragments instead!
			# The two fragments in vendor/etc/vintf/manifest (cas and gpu) live in
			# DEVICE_MANIFEST_FILE, in BoardConfig. The eight in vendor/odm/etc/vintf are
			# left out instead: they are the variants for the different SIM
			# configurations (ss, dsds, tsts, qsqs, with and without SE), the phone uses
			# tsts, and what tsts declares -- android.hardware.radio and
			# vendor.mediatek.hardware.mtkradioex -- our manifest.xml already has, because
			# it was taken from the phone with the manifest already assembled.
			*.apk|system/*.so|*/etc/vintf/*) continue ;;
			*) echo "    vendor/$VENDOR/$DEVICE/proprietary/$f:$(destination "$f") \\" ;;
		esac
	done < "$LIST"

	echo ""
	echo ""
	echo "PRODUCT_PACKAGES += \\"
	{
		while read -r line; do
			case "$line" in ''|'#'*) continue ;; esac
			f="${line#-}"
			case "$f" in *:*) f="${f#*:}" ;; esac
			case "$f" in
				*.apk)       basename "$f" .apk ;;
				system/*.so) basename "$f" .so ;;
			esac
		done < "$LIST"
		if [ -f "$HERE/vendor-override-files.txt" ]; then
			while read -r line; do
				case "$line" in ''|'#'*) continue ;; esac
				name="$(basename "$line")"; echo "s88pro_${name%.so}"
			done < "$HERE/vendor-override-files.txt"
		fi
	} | sort -u | sed 's/^/    /; s/$/ \\/'
	echo ""
} > "$OUT/$DEVICE-vendor.mk"

echo "generated:"
echo "  $OUT/Android.mk"
echo "  $OUT/$DEVICE-vendor.mk"
